name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality-gates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use latest LTS node version
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - name: Setup
        run: pnpm add -g @antfu/ni
      - name: Install
        run: nci
      - name: Lint
        run: nr lint
      - name: Typecheck
        run: nr typecheck

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [lts/*]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Set node version to ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
      - name: Setup
        run: pnpm add -g @antfu/ni
      - name: Install
        run: nci
      - name: Build
        run: nr build
      - name: Test
        run: nr test:ci
